### ISSUE TITLE
Translations dropped beow 90% magic number

### ISSUE THREAD

**Issue by alanef** [alanef/clean-and-simple-contact-form-by-meg-nicholas#13]
Due to latest release and moving some colons

@nepa can you take a look https://translate.wordpress.org/projects/wp-plugins/clean-and-simple-contact-form-by-meg-nicholas/stable/de/default/?filters%5Bstatus%5D=untranslated

**Comment by nepa** [comment]
@alanef: Added the missing translations. Will you ping the polyglots team?

**Comment by alanef** [comment]
pinged
